### PR TITLE
Use direct calls, no more keystrokes

### PR DESCRIPTION
**Pull request by briangonzalez**
@juancaldera

### CODE REVIEW

**Comment by michaelmoussa** [comment]
@briangonzalez tried this out on my machine with US standard keyboard layout and it works great!

**Comment by briangonzalez** [comment]
@michaelmoussa That's great news! 

This doesn't support tabs fully yet, so we'll need to take another pass to manage the IDs.

We're also realizing that our dependency on [jxa](https://github.com/wtfaremyinitials/jxa) is a rough one and could be done better.

**Comment by michaelmoussa** [comment]
@briangonzalez is there any kind of API documentation for these direct calls you added? I had a few ideas for something unrelated to this PR and I couldn't seem to find anything anywhere about `splitHorizontallyWithDefaultProfile`, `currentTab`, etc. Not really sure what is possible for interacting with the iTerm process from Mert.

**Comment by briangonzalez** [comment]
It's a matter of doing a little reverse engineering by mapping the applescript flavor to the jxa flavor.

Here are some examples:

``` shell
set newSession to (split vertically with default profile command "ssh example.com") #apple
newSession.splitVerticallyWithDefaultProfile({ command: "ssh example.com" }) #jxa

set foreground color to {65535, 0, 0, 0} # apple
session.foregroundColor = [65535, 0, 0, 0] # jxa
```

**Comment by david-zacharias** [comment]
Heres what happens on OS X with German standard keyboard layout:

mert-2

The commands find their way to the right panels, ~~but it seems the commands from `.mertrc` won't be executed. Only the change dir.~~

**Comment by briangonzalez** [comment]
@david-zacharias 

This is correct, no?

**Comment by briangonzalez** [comment]
I see the `echo`'s _and_ `cd`'s

**Comment by david-zacharias** [comment]
Stupid me, it's corret... sorry for confusion. So thumbs up for this improvement! 👍

**Comment by briangonzalez** [comment]
Nice – here we go!

**Pull request merged**
